config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  resources :apun_self_evaluations, only: %i[create update destroy]
  resources :bibliographies, only: %i[create update destroy]
  root "blogs#index"
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_one :apun_self_evaluation, class_name: "ApunSelfEvaluation", dependent: :destroy
  has_many :bibliographies, class_name: "Bibliography", dependent: :destroy
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
    @apun_self_evaluation = ApunSelfEvaluation.new
    @bibliography = Bibliography.new
  end

  # GET /blogs/1/edit
  def edit
    @apun_self_evaluation = ApunSelfEvaluation.new
    @bibliography = Bibliography.new
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "Se creó el blog correctamente." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Se editó el blog correctamente." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Se borró el blog correctamente." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_article_card.html.erb
<div class="grid gap-8 lg:grid-cols-2">
  <% @blogs.each do |blog| %>
    <article class="p-6 bg-white rounded-lg border border-gray-200 shadow-md dark:bg-gray-800 dark:border-gray-700">
      <div class="flex justify-between items-center mb-5 text-gray-500">
        <span class="bg-primary-100 text-primary-800 text-xs font-medium inline-flex items-center px-2.5 py-0.5 rounded dark:bg-primary-200 dark:text-primary-800">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="mr-1 w-3 h-3">
            <path stroke-linecap="round" stroke-linejoin="round" d="M12 7.5h1.5m-1.5 3h1.5m-7.5 3h7.5m-7.5 3h7.5m3-9h3.375c.621 0 1.125.504 1.125 1.125V18a2.25 2.25 0 01-2.25 2.25M16.5 7.5V18a2.25 2.25 0 002.25 2.25M16.5 7.5V4.875c0-.621-.504-1.125-1.125-1.125H4.125C3.504 3.75 3 4.254 3 4.875V18a2.25 2.25 0 002.25 2.25h13.5M6 7.5h3v3H6v-3z" />
          </svg>
          Blog
        </span>
        <%# <span class="text-sm">14 days ago</span> %>
      </div>
      <h2 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"><%= link_to "#{blog.title}", blog %></h2>
      <p class="mb-5 font-light text-gray-500 dark:text-gray-400"><%= blog.title %></p>
      <div class="flex justify-between items-center">
        <div class="flex items-center space-x-4">
          <%# <img class="w-7 h-7 rounded-full" src="https://flowbite.s3.amazonaws.com/blocks/marketing-ui/avatars/jese-leos.png" alt="Jese Leos avatar" />
      <span class="font-medium dark:text-white">
        Jese Leos
      </span> %>
        </div>
        <%= link_to blog, class: "inline-flex items-center font-medium text-primary-600 dark:text-primary-500 hover:underline" do %>
          Leer más <svg class="ml-2 w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
        <% end %>
      </div>
    </article>
  <% end %>
</div>

app/views/blogs/_blog.html.erb
<article class="mx-auto sm:w-6/12 lg:mb-16 mb-8">
  <h2 class="text-center mb-4 text-3xl lg:text-4xl tracking-tight font-extrabold text-gray-900 dark:text-white"><%= blog.title %></h2>
  <%# <span class="text-sm">14 days ago</span> %>
  <p class="text-gray-900 sm:text-xl dark:text-gray-800"><%= blog.body %></p>
  <%# <img class="w-7 h-7 rounded-full" src="https://flowbite.s3.amazonaws.com/blocks/marketing-ui/avatars/jese-leos.png" alt="Jese Leos avatar" />
  <span class="font-medium dark:text-white">
    Jese Leos
  </span> %>
</article>

app/views/blogs/_blog_card.html.erb
<div class="grid gap-8 lg:grid-cols-2">
  <% @blogs.each do |blog| %>
    <article class="p-6 bg-white rounded-lg border border-gray-200 shadow-md dark:bg-gray-800 dark:border-gray-700">
      <div class="flex justify-between items-center mb-5 text-gray-500">
        <span class="bg-primary-100 text-primary-800 text-xs font-medium inline-flex items-center px-2.5 py-0.5 rounded dark:bg-primary-200 dark:text-primary-800">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="mr-1 w-3 h-3">
            <path stroke-linecap="round" stroke-linejoin="round" d="M12 7.5h1.5m-1.5 3h1.5m-7.5 3h7.5m-7.5 3h7.5m3-9h3.375c.621 0 1.125.504 1.125 1.125V18a2.25 2.25 0 01-2.25 2.25M16.5 7.5V18a2.25 2.25 0 002.25 2.25M16.5 7.5V4.875c0-.621-.504-1.125-1.125-1.125H4.125C3.504 3.75 3 4.254 3 4.875V18a2.25 2.25 0 002.25 2.25h13.5M6 7.5h3v3H6v-3z" />
          </svg>
          Blog
        </span>
        <%# <span class="text-sm">14 days ago</span> %>
      </div>
      <div class="h-32 truncate">
        <h2 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"><%= link_to "#{blog.title}", blog %></h2>
        <p class="mb-5 font-light text-gray-500 dark:text-gray-400"><%= blog.body %></p>
        <div class="flex justify-between items-center">
          <div class="flex items-center space-x-4">
            <%# <img class="w-7 h-7 rounded-full" src="https://flowbite.s3.amazonaws.com/blocks/marketing-ui/avatars/jese-leos.png" alt="Jese Leos avatar" />
      <span class="font-medium dark:text-white">
        Jese Leos
      </span> %>
          </div>
          <%= link_to blog, class: "inline-flex items-center font-medium text-primary-600 dark:text-primary-500 hover:underline" do %>
            Leer más <svg class="ml-2 w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
          <% end %>
        </div>
      </div>
    </article>
  <% end %>
</div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>
      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <div class="mb-7">
      <%= form.label "Título", style: "display: block", class: "block mb-2 text-xl font-medium text-gray-900 dark:text-gray-400" %>
      <%= form.text_field :title, class: "w-full shadow appearance-none border border-red-500 rounded py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline", placeholder:"Título", aria:"With textarea", autocomplete: 'off' %>
    </div>
    <div class="mb-7">
      <%= form.label "Cuerpo", style: "display: block", class: "block mb-2 text-xl font-medium text-gray-900 dark:text-gray-400" %>
      <%= form.text_area :body, class: "w-full text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", placeholder:"Cuerpo", aria:"With textarea", autocomplete: 'off' %>
    </div>
    <button>
      <%= form.submit "Crear blog", class: "text-white bg-blue-700 mb-10 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" %>
    </button>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="text-center mx-auto sm:w-6/12">
  <h2 class="mb-4 text-3xl lg:text-4xl tracking-tight font-extrabold text-gray-900 dark:text-white">Editar blog</h2>
  <%= render "form", blog: @blog %>
  <h2 class="mb-4 text-xl lg:text-2xl tracking-tight font-extrabold text-gray-900 dark:text-white">Editar Autoevaluación</h2>
  <%= render "apun_self_evaluations/form", apun_self_evaluation: @apun_self_evaluation, blog: @blog %>
  <div>
    <%= link_to "Leer el blog", @blog, class: "font-medium text-primary-600 dark:text-primary-500 hover:underline" %> |
    <%= link_to "Todos los blogs", blogs_path, class: "font-medium text-primary-600 dark:text-primary-500 hover:underline" %>
  </div>
</div>

app/views/blogs/index.html.erb
<div class="mx-auto max-w-screen-sm text-center lg:mb-16 mb-8">
  <h2 class="mb-4 text-3xl lg:text-4xl tracking-tight font-extrabold text-gray-900 dark:text-white">Blogs Cátedra APUN 50-Años</h2>
  <%= link_to "Nuevo blog", new_blog_path, class: "inline-flex items-center font-medium text-primary-600 dark:text-primary-500 hover:underline" %>
</div>
<%= render 'blog_card', resource: @blogs %>

app/views/blogs/new.html.erb
<div class="text-center mx-auto sm:w-6/12">
  <h2 class="mb-4 text-3xl lg:text-4xl tracking-tight font-extrabold text-gray-900 dark:text-white">Crear blog</h2>
  <%= render "form", blog: @blog %>
  <% if @blog.apun_self_evaluation.present? %>
    <h2 class="mb-4 text-xl lg:text-2xl tracking-tight font-extrabold text-gray-900 dark:text-white">Autoevaluación</h2>
    <%= render "apun_self_evaluations/apun_self_evaluation", apun_self_evaluation: @blog.apun_self_evaluation %>
  <% else %>
    <h2 class="mb-4 text-xl lg:text-2xl tracking-tight font-extrabold text-gray-900 dark:text-white">Agregar Autoevaluación</h2>
    <%= render "apun_self_evaluations/form", apun_self_evaluation: @apun_self_evaluation, blog: @blog %>
  <% end %>
  <div>
    <%= link_to "Todos los blogs", blogs_path, class: "font-medium text-primary-600 dark:text-primary-500 hover:underline" %>
  </div>
</div>

app/views/blogs/show.html.erb
<%= render @blog %>
<% if @blog.apun_self_evaluation.present? %>
  <div class="text-center mx-auto sm:w-6/12">
    <h2 class="mb-4 text-xl lg:text-2xl tracking-tight font-extrabold text-gray-900 dark:text-white">Autoevaluación</h2>
    <%= render "apun_self_evaluations/apun_self_evaluation", apun_self_evaluation: @blog.apun_self_evaluation %>
  </div>
<% end %>
<div class="text-center">
  <%= link_to "Editar este blog", edit_blog_path(@blog), class: "font-medium text-primary-600 dark:text-primary-500 hover:underline" %> |
  <%= link_to "Todos los blogs", blogs_path, class: "font-medium text-primary-600 dark:text-primary-500 hover:underline" %>
  <%= button_to "Borrar este blog", @blog, class: "font-medium text-primary-600 dark:text-primary-500 hover:underline", method: :delete %>
</div>